@echo off

set CMAKE_MAKE_PROGRAM=Y:\MinGW\bin\mingw32-make.exe
set CMAKE_ANDROID_NDK=Y:\android-ndk-r10e
REM armeabi-v7a | x86 | arm64-v8a | x86_64
set ANDROID_ABI=armeabi-v7a


set PROJECT_PATH=%~dp0
set OPENCV_BUILD=%PROJECT_PATH%_build_android\OpenCV_%ANDROID_ABI%
set DLIB_BUILD=%PROJECT_PATH%_build_android\DLib_%ANDROID_ABI%
set OPENCVEXTERN_BUILD=%PROJECT_PATH%_build_android\OpenCVExtern_%ANDROID_ABI%
set CMAKE_TOOLCHAIN_FILE=%PROJECT_PATH%utils\toolchains\toolchain.android.cmake


echo Building OpenCV...

if not exist "%OPENCV_BUILD%" (
	mkdir "%OPENCV_BUILD%"
)

cd %OPENCV_BUILD%

cmake -G "MinGW Makefiles" -DWITH_VTK=OFF -DWITH_1394=OFF -DWITH_GSTREAMER=OFF DWITH_V4L=OFF -DWITH_QT=OFF -DWITH_GTK=OFF -DWITH_GPHOTO2=OFF -DWITH_MATLAB=OFF -DWITH_TIFF=OFF -DWITH_JASPER=OFF -DWITH_JPEG=OFF -DWITH_PNG=OFF -DWITH_CUDA=OFF -DBUILD_opencv_hdf=OFF -DBUILD_OPENCV_JAVA=OFF -DBUILD_OPENCV_WORLD=OFF -DBUILD_OPENCV_PYTHON=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_opencv_apps=OFF -DBUILD_ANDROID_EXAMPLES=OFF -DBUILD_DOCS=OFF  -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_WITH_DEBUG_INFO=OFF -Wno-deprecated -DCMAKE_TRY_COMPILE_PLATFORM_VARIABLES=CMAKE_WARN_DEPRECATED -DOPENCV_EXTRA_MODULES_PATH="%PROJECT_PATH%source\contrib-3.2.0\modules"  -DCMAKE_ANDROID_NDK=%CMAKE_ANDROID_NDK% -DCMAKE_TOOLCHAIN_FILE=%CMAKE_TOOLCHAIN_FILE% -DANDROID_ABI=%ANDROID_ABI% -DANDROID_STL=gnustl_static -DCMAKE_INSTALL_PREFIX:PATH="%PROJECT_PATH%temp\android\%ANDROID_ABI%\libs\opencv-3.2.0" -DCMAKE_BUILD_TYPE=Release "%PROJECT_PATH%source\opencv-3.2.0" -DCMAKE_MAKE_PROGRAM=%CMAKE_MAKE_PROGRAM%

mingw32-make -j4
mingw32-make install

echo Building DLib...
if not exist "%DLIB_BUILD%" (
	mkdir "%DLIB_BUILD%"
)

cd %DLIB_BUILD%

cmake -G "MinGW Makefiles" -Wno-deprecated -DCMAKE_TRY_COMPILE_PLATFORM_VARIABLES=CMAKE_WARN_DEPRECATED  -DDLIB_STATIC_ONLY=ON -DDLIB_ENABLE_ASSERTS=OFF -DDLIB_ENABLE_STACK_TRACE=OFF -DDLIB_USE_CUDA=OFF -DDLIB_NO_GUI_SUPPORT=ON -DDLIB_PNG_SUPPORT=OFF -DDLIB_GIF_SUPPORT=OFF -DDLIB_JPEG_SUPPORT=OFF -DDLIB_LINK_WITH_SQLITE3=OFF -DCMAKE_ANDROID_NDK=%CMAKE_ANDROID_NDK% -DCMAKE_TOOLCHAIN_FILE=%CMAKE_TOOLCHAIN_FILE% -DANDROID_ABI=%ANDROID_ABI% -DANDROID_STL=gnustl_static -DCMAKE_INSTALL_PREFIX:PATH="%PROJECT_PATH%temp\android\%ANDROID_ABI%\libs\dlib-19.4" -DCMAKE_BUILD_TYPE=Release "%PROJECT_PATH%source\dlib-19.4" -DCMAKE_MAKE_PROGRAM=%CMAKE_MAKE_PROGRAM%

mingw32-make -j4
mingw32-make install

echo Building OpenCVExtern...
if not exist "%OPENCVEXTERN_BUILD%" (
	mkdir "%OPENCVEXTERN_BUILD%"
)

cd %OPENCVEXTERN_BUILD%
cmake -G "MinGW Makefiles" -Wno-deprecated -DCMAKE_TRY_COMPILE_PLATFORM_VARIABLES=CMAKE_WARN_DEPRECATED -DCMAKE_PREFIX_PATH="%PROJECT_PATH%temp\android\%ANDROID_ABI%\libs"  -DCMAKE_ANDROID_NDK=%CMAKE_ANDROID_NDK% -DCMAKE_TOOLCHAIN_FILE=%CMAKE_TOOLCHAIN_FILE% -DANDROID_ABI=%ANDROID_ABI% -DANDROID_STL=gnustl_static -DCMAKE_INSTALL_PREFIX:PATH="%PROJECT_PATH%temp\android\%ANDROID_ABI%\libs\sharpextern-1.1" -DCMAKE_BUILD_TYPE=Release "%PROJECT_PATH%source\sharpextern-1.1" -DCMAKE_MAKE_PROGRAM=%CMAKE_MAKE_PROGRAM%

mingw32-make -j4
mingw32-make install

cd %PROJECT_PATH%

