IOS_ARCH=armv7
OPENCV_VERSION=4.1.0
OPENCV_CONTRIB_VERSION=4.1.0
DLIB_VERSION=19.17
SHARPEXTERN_VERSION=4.1.0
IPHONEOS_DEPLOYMENT_TARGET=7.0

CMAKE_TOOLCHAIN_FILE=
# paths

PROJECT_PATH=$PWD
OPENCV_BUILD="$PROJECT_PATH/_build_ios/OpenCV_$OPENCV_VERSION_$IOS_ARCH"
DLIB_BUILD="$PROJECT_PATH/_build_ios/DLib_$DLIB_VERSION_$IOS_ARCH"
OPENCVEXTERN_BUILD="$PROJECT_PATH/_build_ios/OpenCVExtern_$SHARPEXTERN_VERSION_$IOS_ARCH"
CMAKE_TOOLCHAIN_FILE="$PROJECT_PATH/utils/toolchains/toolchain.ios.cmake"

# this function help to execute some command as error-fatal
function required {
    "$@"
    local status=$?
    if [ $status -ne 0 ]; then
        echo "FATAL ERROR: \"$@\" <-- command failed"
        exit 1
    fi
}

echo Building OpenCV...

if [ ! -d "$OPENCV_BUILD" ]; then
		required mkdir -p "$OPENCV_BUILD"
fi
cd "$OPENCV_BUILD"

cmake -G "Xcode" -DWITH_VTK=OFF -DWITH_1394=OFF -DWITH_GSTREAMER=OFF DWITH_V4L=OFF -DWITH_QT=OFF -DWITH_GTK=OFF -DWITH_GPHOTO2=OFF -DWITH_MATLAB=OFF -DWITH_TIFF=OFF -DWITH_JASPER=OFF -DWITH_JPEG=OFF -DWITH_PNG=OFF -DWITH_CUDA=OFF -DBUILD_opencv_hdf=OFF -DBUILD_OPENCV_JAVA=OFF -DBUILD_OPENCV_WORLD=OFF -DBUILD_OPENCV_PYTHON=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_opencv_apps=OFF -DBUILD_ANDROID_EXAMPLES=OFF -DBUILD_DOCS=OFF  -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_WITH_DEBUG_INFO=OFF -Wno-deprecated -DCMAKE_TRY_COMPILE_PLATFORM_VARIABLES=CMAKE_WARN_DEPRECATED -DOPENCV_EXTRA_MODULES_PATH="$PROJECT_PATH/source/contrib-$OPENCV_CONTRIB_VERSION/modules" -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE -DIOS_ARCH=$IOS_ARCH -DCPU_BASELINE=DETECT -DCMAKE_C_FLAGS=-fembed-bitcode -DCMAKE_CXX_FLAGS=-fembed-bitcode -DIPHONEOS_DEPLOYMENT_TARGET="$IPHONEOS_DEPLOYMENT_TARGET" -DCMAKE_INSTALL_PREFIX:PATH="$PROJECT_PATH/temp/ios/$IOS_ARCH/libs/opencv-$OPENCV_VERSION" -DCMAKE_BUILD_TYPE=Release "$PROJECT_PATH/source/opencv-$OPENCV_VERSION"

xcodebuild IPHONEOS_DEPLOYMENT_TARGET="$IPHONEOS_DEPLOYMENT_TARGET" ARCHS=$IOS_ARCH -target install -sdk iphoneos -configuration Release -parallelizeTargets -jobs 4


echo Building OpenCVExtern...

if [ ! -d "$OPENCVEXTERN_BUILD" ]; then
		required mkdir -p "$OPENCVEXTERN_BUILD"
fi
cd "$OPENCVEXTERN_BUILD"
cmake -G "Xcode" -Wno-deprecated -DCMAKE_TRY_COMPILE_PLATFORM_VARIABLES=CMAKE_WARN_DEPRECATED -DCMAKE_PREFIX_PATH="$PROJECT_PATH/temp/ios/$IOS_ARCH/libs" -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE -DIOS_ARCH=$IOS_ARCH -DCPU_BASELINE=DETECT -DCMAKE_C_FLAGS=-fembed-bitcode -DCMAKE_CXX_FLAGS=-fembed-bitcode -DIPHONEOS_DEPLOYMENT_TARGET="$IPHONEOS_DEPLOYMENT_TARGET" -DCMAKE_INSTALL_PREFIX:PATH="$PROJECT_PATH/temp/ios/$IOS_ARCH/libs/sharpextern-$SHARPEXTERN_VERSION" -DCMAKE_BUILD_TYPE=Release "$PROJECT_PATH/source/sharpextern-$SHARPEXTERN_VERSION"

xcodebuild IPHONEOS_DEPLOYMENT_TARGET="$IPHONEOS_DEPLOYMENT_TARGET" ARCHS=$IOS_ARCH -target install -sdk iphoneos -configuration Release -parallelizeTargets -jobs 4




